# Generated by Django 4.1.3 on 2024-05-15 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_game_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_type',
            new_name='GameType',
        ),
    ]
